### ISSUE TITLE
Retweets all at once, how to slow it down?

### ISSUE THREAD

**Issue by ChaseyChaser** [basti2342/retweet-bot#15]
How can I slow down the retweets to once every 15 minutes? Currently it is spamming them out all at once.

**Comment by basti2342** [comment]
As a short hack you could just add
`break`
in the for-loop after [line 45](https://github.com/basti2342/retweet-bot/blob/8c472a4f035d265235f356b612d51a252c4d0914/retweet.py#L45). This way the list of Tweets contains only 1 Tweet each time the script is called. Now call it every 15 minutes via crontab (if you're using something Unix-like) or task scheduler (for Windows).

**Comment by mikeyny** [comment]
Another hack you could use instead of using ```break``` is specifying how many tweet you want on line 40
```python
timelineIterator = tweepy.Cursor(api.search, q=hashtag, since_id=savepoint, lang=tweetLanguage).items(5)
# for five twits
timelineIterator = tweepy.Cursor(api.search, q=hashtag, since_id=savepoint, lang=tweetLanguage).items(25)
# for 25 twits
```
