### ISSUE TITLE
regexing the search query

### ISSUE THREAD

**Issue by AnotherLizard** [basti2342/retweet-bot#9]
Hi. Is it possible to re the search query for a tighter pattern match? Or to have it search for multiple queries? At the moment I am post processing already pulled tweets but this is a little annoying due to I am limited to how many tweets I can pull in a timeframe.

**Comment by basti2342** [comment]
Hi AnotherLizard,

if I understand you correct, you want to use a regular expression in the search query? The Twitter API does not support this, so there will be no such feature unfortunately.

Regards,
basti2342
